package com.example.worker.notification.api.controller;
import com.example.worker.notification.api.request.MarkNotificationsReadRequest; import com.example.worker.notification.api.response.*; import com.example.worker.notification.application.service.*; import com.example.worker.notification.application.port.NotificationStreamSubscriber;
import jakarta.validation.Valid; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.method.annotation.SseEmitter; import java.util.*;
@RestController @org.springframework.validation.annotation.Validated @RequestMapping("/api/projects/{projectId}/notifications") public class ProjectNotificationController {
 private final NotificationQueryService query; private final NotificationCommandService command; private final NotificationStreamSubscriber hub;
 public ProjectNotificationController(NotificationQueryService query,NotificationCommandService command,NotificationStreamSubscriber hub){this.query=query;this.command=command;this.hub=hub;}
 @GetMapping public NotificationPageResponse list(@PathVariable UUID projectId,@RequestParam(required=false) String cursor,@RequestParam(defaultValue="20") @jakarta.validation.constraints.Min(1) @jakarta.validation.constraints.Max(100) int size){validateCursor(cursor);return NotificationPageResponse.from(query.latest(projectId,cursor,size));}
 @GetMapping("/unread-count") public UnreadNotificationCountResponse unread(@PathVariable UUID projectId){return new UnreadNotificationCountResponse(query.unreadCount(projectId));}
 @PostMapping("/{notificationId}/read") @ResponseStatus(HttpStatus.NO_CONTENT) public void read(@PathVariable UUID projectId,@PathVariable UUID notificationId){command.markRead(projectId,notificationId);}
 @PostMapping("/read") @ResponseStatus(HttpStatus.NO_CONTENT) public void readAll(@PathVariable UUID projectId,@Valid @RequestBody MarkNotificationsReadRequest request){command.markRead(projectId,request.notificationIds());}
 @GetMapping(value="/stream",produces=MediaType.TEXT_EVENT_STREAM_VALUE) public SseEmitter stream(@PathVariable UUID projectId,@RequestHeader(value="Last-Event-ID",required=false) String last){validateCursor(last); SseEmitter emitter=hub.subscribe(projectId); if(last==null)return emitter; var replay=query.replay(projectId,Long.parseLong(last)); if(replay.reset())hub.reset(emitter); else replay.events().forEach(n->hub.replay(emitter,n)); return emitter;}
 private static void validateCursor(String cursor){if(cursor==null)return; try{if(Long.parseLong(cursor)<1)throw new NumberFormatException();}catch(NumberFormatException e){throw new org.springframework.web.server.ResponseStatusException(HttpStatus.BAD_REQUEST,"cursor must be a positive event id");}}
}
