package com.example.worker.scm.infrastructure.github;

import com.example.worker.scm.application.SourceControlPlugin.CreateDraftPullRequestCommand;
import com.example.worker.scm.application.SourceControlPlugin.MergePullRequestCommand;
import com.example.worker.scm.application.SourceControlPlugin.PullRequestResult;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@DisplayName("GitHubCliSourceControlPlugin")
class GitHubCliSourceControlPluginTest {

    private final List<String[]> executedCommands = new ArrayList<>();
    private RecordingCommandExecutor executor;
    private GitHubCliSourceControlPlugin plugin;

    @BeforeEach
    void setUp() {
        executedCommands.clear();
        executor = new RecordingCommandExecutor();
        plugin = new GitHubCliSourceControlPlugin(executor);
    }

    private CreateDraftPullRequestCommand createCommand(String idempotencyKey, String baseBranch) {
        return new CreateDraftPullRequestCommand(
                idempotencyKey, "/workspace/run-1", baseBranch, "feature/run-1",
                "Implement run-1", "Generated by agent", true);
    }

    @Test
    @DisplayName("create 호출은 지정된 base 브랜치로 gh pr create --draft 명령을 실행한다 (main 하드코딩 아님)")
    void createDraftPullRequest_buildsCommandWithGivenBaseBranch() {
        executor.nextResult = "https://github.com/example/repo/pull/1\n";

        PullRequestResult result = plugin.createDraftPullRequest(createCommand("key-1", "develop"));

        assertThat(result.url()).isEqualTo("https://github.com/example/repo/pull/1");
        assertThat(result.status()).isEqualTo("DRAFT");
        assertThat(executedCommands).hasSize(1);
        assertThat(executedCommands.get(0)).containsSubsequence("--base", "develop");
        assertThat(String.join(" ", executedCommands.get(0))).doesNotContain("main");
    }

    @Test
    @DisplayName("qaPassed=false이면 Draft PR을 생성하지 않고 예외를 던진다")
    void createDraftPullRequest_withoutQaPassed_isRejected() {
        CreateDraftPullRequestCommand command = new CreateDraftPullRequestCommand(
                "key-2", "/workspace/run-2", "main", "feature/run-2", "title", "body", false);

        assertThatThrownBy(() -> plugin.createDraftPullRequest(command))
                .isInstanceOf(IllegalStateException.class);
        assertThat(executedCommands).isEmpty();
    }

    @Test
    @DisplayName("같은 idempotencyKey로 반복 create 호출하면 명령을 재실행하지 않고 기존 결과를 반환한다")
    void createDraftPullRequest_repeatedCall_isIdempotent() {
        executor.nextResult = "https://github.com/example/repo/pull/2\n";

        PullRequestResult first = plugin.createDraftPullRequest(createCommand("key-3", "main"));
        PullRequestResult second = plugin.createDraftPullRequest(createCommand("key-3", "main"));

        assertThat(second).isEqualTo(first);
        assertThat(executedCommands).hasSize(1);
    }

    @Test
    @DisplayName("Draft PR이 존재하지 않으면 merge는 거부되고 merge 명령이 실행되지 않는다")
    void mergePullRequest_withoutExistingDraft_isRejected() {
        executor.nextResult = "{}"; // gh pr view finds nothing

        MergePullRequestCommand command = new MergePullRequestCommand("key-4", "/workspace/run-4", "feature/run-4");

        assertThatThrownBy(() -> plugin.mergePullRequest(command))
                .isInstanceOf(IllegalStateException.class);
        assertThat(executedCommands).noneMatch(cmd -> List.of(cmd).contains("merge"));
    }

    @Test
    @DisplayName("Draft PR이 존재하면 gh pr merge 명령을 실행한다")
    void mergePullRequest_withExistingDraft_executesMergeCommand() {
        executor.results.add("{\"url\":\"https://github.com/example/repo/pull/5\",\"state\":\"OPEN\"}");
        executor.results.add("merged");

        PullRequestResult result = plugin.mergePullRequest(
                new MergePullRequestCommand("key-5", "/workspace/run-5", "feature/run-5"));

        assertThat(result.status()).isEqualTo("MERGED");
        assertThat(result.url()).isEqualTo("https://github.com/example/repo/pull/5");
        assertThat(executedCommands).hasSize(2);
        assertThat(executedCommands.get(1)).containsSubsequence("merge", "feature/run-5");
    }

    @Test
    @DisplayName("같은 idempotencyKey로 반복 merge 호출하면 merge 명령을 재실행하지 않는다")
    void mergePullRequest_repeatedCall_isIdempotent() {
        executor.results.add("{\"url\":\"https://github.com/example/repo/pull/6\",\"state\":\"OPEN\"}");
        executor.results.add("merged");

        MergePullRequestCommand command = new MergePullRequestCommand("key-6", "/workspace/run-6", "feature/run-6");
        PullRequestResult first = plugin.mergePullRequest(command);
        PullRequestResult second = plugin.mergePullRequest(command);

        assertThat(second).isEqualTo(first);
        assertThat(executedCommands).hasSize(2); // view + merge, 두 번째 merge 호출은 실행되지 않음
    }

    @Test
    @DisplayName("getPullRequest는 gh pr view의 JSON 출력을 파싱한다")
    void getPullRequest_parsesJsonOutput() {
        executor.nextResult = "{\"url\":\"https://github.com/example/repo/pull/7\",\"state\":\"OPEN\"}";

        PullRequestResult result = plugin.getPullRequest("/workspace/run-7", "feature/run-7");

        assertThat(result.url()).isEqualTo("https://github.com/example/repo/pull/7");
        assertThat(result.status()).isEqualTo("OPEN");
    }

    @Test
    @DisplayName("getPullRequest는 PR이 없으면 null을 반환한다 (예외가 아님)")
    void getPullRequest_noPullRequest_returnsNull() {
        executor.nextResult = "{}";

        PullRequestResult result = plugin.getPullRequest("/workspace/run-8", "feature/run-8");

        assertThat(result).isNull();
    }

    private final class RecordingCommandExecutor implements GitHubCliSourceControlPlugin.CommandExecutor {

        private String nextResult = "";
        private final List<String> results = new ArrayList<>();

        @Override
        public String execute(String workDir, String... command) {
            executedCommands.add(command);
            if (!results.isEmpty()) {
                return results.remove(0);
            }
            return nextResult;
        }
    }
}
